export const UPDATE_STORE = 'UPDATE_STORE';
export const RESET_STORE = 'RESET_STORE';
export const UPDATE_CONTAINER = 'UPDATE_CONTAINER';
export const UPDATE_TAB = 'UPDATE_TAB';
export const REMOVE_CONTAINER = 'REMOVE_CONTAINER';
